spring:
  application:
    name: gateway
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
    appname: gateway
  client:
    healthcheck:
      enabled: true
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
